plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.bearbellengine'
version = '0.1.0'

android {
  namespace "expo.modules.bearbellengine"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lint {
    abortOnError = false
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}
